import SessionProvider from '@/providers/SessionProvider';
import CoinsProvider from '@/providers/crypto/CoinsProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import Sidebar from '../components/Sidebar/Sidebar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Crypto Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <CoinsProvider>
            <div className="flex overflow-hidden">
              <Sidebar />
              {children}
            </div>
          </CoinsProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
